### ISSUE TITLE
Update app dependencies

### ISSUE THREAD

**Issue by alxekb** [unicollezione/crm#22]
- [ ] Cleanup app config
- [ ] Update docker config
- [ ] Make it work
- [ ] Add readme

closes #20

**Comment by alxekb** [comment]
@sas2job давая сделаем отдельный файл с докер конфигом базы, чтобы в репо было `datbase.yml` и `database.docker.yml` или еще как-нибудь по другому, чтобы прод точно выжил после деплоя.


https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development

https://github.com/bibendi/dip-example-rails/blob/master/config/database.yml

**Comment by sas2job** [comment]
> @sas2job давая сделаем отдельный файл с докер конфигом базы, чтобы в репо было `datbase.yml` и `database.docker.yml` или еще как-нибудь по другому, чтобы прод точно выжил после деплоя.

Сделал два конфига.
