### ISSUE TITLE
Генерация pdf документа

### ISSUE THREAD

**Issue by sas2job** [unicollezione/crm#4]
На основе данных полученных через API Notion либо имеющихся данных создавать pdf документ. Первоначально содержащий только build process(описание технологии производства).
Определиться как и где хранить файлы pdf.

**Comment by Aleh13** [comment]
Какие данные нужно генерировать в pdf файл, как должна выглядеть карточка заказа(макет)?

**Comment by Aleh13** [comment]
Данные для карточки будут браться из БД?

**Comment by voveng** [comment]
Рендерится вьюха она берет данные из базы с картинкой , вот эту вью и надо будет делать pdf . Насколько я понимаю идею.

**Comment by Aleh13** [comment]
Я представлял что pdf рендерится сразу из БД так как у нас api, мы даем значения для пошива боту, а он сразу выдает нам pdf файл-карточку, хотя так наверное сложнее реализовать чем сделать pdf из вьюхи. Вот мне непонятно как работает наше приложение и из каких частей состоит, поэтому был бы полезен созвон.

**Comment by alxekb** [comment]
Давай просто научим приложение генерить пдфку с текстом "Hello world" и складывать ее в бакет уже это - достаточный объем работы. Креды в бакет есть у @sas2job
Как только я увижу ПР - объясню дальше. 
@Aleh13
